# Generated by Django 4.2 on 2023-04-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("DEALER", "Dealer"),
                    ("CUSTOMER", "Customer"),
                    ("CARSHOWROOM", "CarShowRoom"),
                ],
                default="CUSTOMER",
            ),
        ),
    ]
