version: "3.9"

services:
  web:
    build: CarShowRoom
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn CarShowRoom.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - env/db.env
      - env/backends.env
    volumes:
      - ./CarShowRoom:/app
      - static:/static
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/db.env
    ports:
      - "5555:5432"
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
       - "6379:6379"
    restart: always
  celery:
    build: CarShowRoom
    command: celery -A CarShowRoom worker -l info
    volumes:
      - ./CarShowRoom:/app
    env_file:
      - env/db.env
      - env/backends.env
    depends_on:
      - redis
  celery-beat:
    build: CarShowRoom
    command: celery -A CarShowRoom beat -l info
    volumes:
      - ./CarShowRoom:/app
    env_file:
      - env/db.env
      - env/backends.env
    depends_on:
      - redis
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static:


