version: "3.9"

services:
  web:
    build: CarShowRoom
    command: bash -c "./manage.py migrate &&while :; do exec ./manage.py runserver 0.0.0.0:8000; done;"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - env/db.env
    volumes:
      - ./CarShowRoom:/app
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/db.env
    ports:
      - "5555:5432"

volumes:
  postgres_data:
