# Generated by Django 4.2 on 2023-04-12 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 582533, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 582571, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("doors_amount", models.IntegerField(default=3)),
                ("engine_power", models.IntegerField()),
                (
                    "engine_type",
                    models.CharField(
                        choices=[
                            ("F", "Fuel"),
                            ("D", "Diesel"),
                            ("H", "Hybrid"),
                            ("G", "Gas"),
                        ],
                        default="F",
                        max_length=20,
                    ),
                ),
                ("year_produced", models.IntegerField()),
                (
                    "price_category",
                    models.CharField(
                        choices=[("C", "Cheap"), ("M", "Medium"), ("L", "Luxury")],
                        default="M",
                        max_length=20,
                    ),
                ),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("max_speed", models.IntegerField()),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 583732, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 583748, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "car_brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cars",
                        to="cars.carbrand",
                    ),
                ),
            ],
        ),
    ]
