# Generated by Django 4.2 on 2023-04-14 06:44

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 14, 6, 44, 9, 725403, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="carbrand",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 14, 6, 44, 9, 725403, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
