# Generated by Django 4.2 on 2023-04-12 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarShowRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("city", models.CharField(max_length=40)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("address", models.TextField()),
                ("margin", models.FloatField()),
                (
                    "money_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "price_category",
                    models.CharField(
                        choices=[("C", "Cheap"), ("M", "Medium"), ("L", "Luxury")],
                        default="M",
                        max_length=10,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 585926, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 585943, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("year_founded", models.IntegerField()),
                ("money_turnover", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 586727, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 586743, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShowroomCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("car_amount", models.IntegerField(default=1)),
                ("car_sold", models.IntegerField(default=0)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.car"
                    ),
                ),
                (
                    "car_showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sellers.carshowroom",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sellers.dealer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShowroomBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.carbrand"
                    ),
                ),
                (
                    "car_showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sellers.carshowroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DealerShowroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deals_amount", models.IntegerField(default=1)),
                ("discount", models.FloatField(default=0)),
                (
                    "car_showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sellers.carshowroom",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sellers.dealer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DealerCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("car_sold", models.IntegerField(default=0)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.car"
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sellers.dealer"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dealer",
            name="car_list",
            field=models.ManyToManyField(
                related_name="dealers", through="sellers.DealerCar", to="cars.car"
            ),
        ),
        migrations.AddField(
            model_name="carshowroom",
            name="car_brands",
            field=models.ManyToManyField(
                related_name="car_showrooms",
                through="sellers.ShowroomBrand",
                to="cars.carbrand",
            ),
        ),
        migrations.AddField(
            model_name="carshowroom",
            name="car_list",
            field=models.ManyToManyField(
                related_name="showrooms", through="sellers.ShowroomCar", to="cars.car"
            ),
        ),
    ]
