# Generated by Django 4.2 on 2023-04-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carshowroom",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="carshowroom",
            name="price_category",
            field=models.CharField(
                choices=[
                    ("CHEAP", "Cheap"),
                    ("MEDIUM", "Medium"),
                    ("LUXURY", "Luxury"),
                ],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
