# Generated by Django 4.2 on 2023-04-26 07:16

import core.validation.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0002_discount_discountcar_discount_cars_discount_dealer"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="discount_percent",
            field=models.IntegerField(
                default=4, validators=[core.validation.validators.validate_discount]
            ),
            preserve_default=False,
        ),
    ]
