# Generated by Django 4.2 on 2023-04-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0002_alter_carshowroom_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carshowroom",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dealer",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
