# Generated by Django 4.2 on 2023-04-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0004_alter_discount_car_showroom_alter_discount_dealer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroomcar",
            name="dealer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sellers.dealer",
            ),
        ),
    ]
