# Generated by Django 4.2 on 2023-05-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0009_supplyhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplyhistory",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
