# Generated by Django 4.2 on 2023-04-12 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cars", "0001_initial"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "money_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "date_register",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 590980, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 591002, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 591620, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 591635, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="cars.car",
                    ),
                ),
                (
                    "made_by_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resulted_price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 592153, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 12, 8, 29, 13, 592169, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "car_showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sellers.carshowroom",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="customers.offer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShowroomCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deals_amount", models.IntegerField(default=1)),
                ("discount", models.FloatField(default=0)),
                (
                    "car_showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sellers.carshowroom",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="showrooms",
            field=models.ManyToManyField(
                related_name="customers",
                through="customers.ShowroomCustomer",
                to="sellers.carshowroom",
            ),
        ),
    ]
