# Generated by Django 4.2 on 2023-04-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("sellers", "0001_initial"),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="sold_by_showroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="sellers.carshowroom",
            ),
        ),
        migrations.AddField(
            model_name="showroomcustomer",
            name="car_showroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sellers.carshowroom"
            ),
        ),
        migrations.AddField(
            model_name="showroomcustomer",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customers.customer"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="cars.car",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="made_by_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="balance",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="balance_customer",
                to="sellers.balance",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="showrooms",
            field=models.ManyToManyField(
                related_name="customers",
                through="customers.ShowroomCustomer",
                to="sellers.carshowroom",
            ),
        ),
    ]
