# Generated by Django 4.2 on 2023-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
