# Generated by Django 4.2 on 2023-04-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_alter_offer_created_at_alter_offer_modified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
